# # HEAD
# import streamlit as st
# from groq import Groq
# import os
# from dotenv import load_dotenv

# load_dotenv()

# # 🔹 Page UI
# st.set_page_config(page_title="KimiAI Bot", page_icon=":robot_face:", layout="centered")
# st.title("KimiAI Bot generated by UmarImam")
# st.caption("Powered by Groq API")

# client = Groq(api_key=os.getenv("GROQ_API_KEY"))

# # 🔹 Session Memory
# if "messages" not in st.session_state:
#     st.session_state.messages = []

# # 🔹 Display Chat History
# for msg in st.session_state.messages:
#     with st.chat_message(msg["role"]):
#         st.markdown(msg["content"])

# # 🔹 User Input
# prompt = st.chat_input("Ask me anything...")

# if prompt:
#     # Store user message
#     st.session_state.messages.append({"role": "user", "content": prompt})

#     # 👇 Immediately show user message
#     with st.chat_message("user"):
#         st.markdown(prompt)

#     full_response = ""

#     stream = client.chat.completions.create(
#         model="moonshotai/kimi-k2-instruct-0905",
#         messages=st.session_state.messages,
#         max_completion_tokens=2048,
#         temperature=0.7,
#         stream=True
#     )

#     with st.chat_message("assistant"):
#         placeholder = st.empty()

#         for chunk in stream:
#             if chunk.choices and chunk.choices[0].delta.content:
#                 token = chunk.choices[0].delta.content
#                 full_response += token
#                 placeholder.markdown(full_response)

#     if full_response.strip() == "":
#         full_response = "No response from the model"

#     st.session_state.messages.append(
#         {"role": "assistant", "content": full_response}
#     )

# # 🔹 Footer
# st.markdown("---")
# st.markdown(
#     "<div style='text-align: center; color: gray;'>Made with ❤️ — KimiAI Bot generated by UmarImam</div>",
#     unsafe_allow_html=True
# )
# =======

# # above was sir code and below is mine code


import streamlit as st
from groq import Groq
import os
from dotenv import load_dotenv
from datetime import datetime

load_dotenv()

# ---------------------------
# Page Config
# ---------------------------
st.set_page_config(
    page_title="KimiAI Bot",
    page_icon="🤖",
    layout="centered"
)

st.markdown("""
<style>
.block-container {
    padding-top: 1rem;
}
</style>
""", unsafe_allow_html=True)

st.markdown("""
<div style="text-align: center;">
    <h1>KimiAI Bot 🤖</h1>
    <p style="color: gray;">Powered by Groq API</p>
</div>
""", unsafe_allow_html=True)

# ---------------------------
# Sidebar (Clear Chat Button)
# ---------------------------
with st.sidebar:
    st.title("⚙️ Settings")

    # New Chat Button
    if st.button("➕ New Chat"):
        st.session_state.messages = []
        st.rerun()

    # Clear Chat Button
    if st.button("🗑️ Clear Chat"):
        st.session_state.messages = []
        st.rerun()
 # Push footer to bottom
    st.markdown("<br><br><br><br><br>", unsafe_allow_html=True)
    st.markdown(
        "<div style='text-align:center; font-size:18px; color:gray;'>"
        "Made with ❤️ — KimiAI Bot Developed by UmarImam"
        "</div>",
        unsafe_allow_html=True
    )
    
# ---------------------------
# Groq Client
# ---------------------------
client = Groq(api_key=os.getenv("GROQ_API_KEY"))

# ---------------------------
# Session State
# ---------------------------
if "messages" not in st.session_state:
    st.session_state.messages = []

# ---------------------------
# Display Chat History
# ---------------------------
for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])

# ---------------------------
# User Input
# ---------------------------
prompt = st.chat_input("Ask me anything...")

if prompt:

    # Append user message
    st.session_state.messages.append({"role": "user", "content": prompt})

    with st.chat_message("user"):
        st.markdown(prompt)

    # Assistant response
    with st.chat_message("assistant"):
        placeholder = st.empty()
        full_response = ""

        with st.spinner("Kimi is thinking..."):

            stream = client.chat.completions.create(
                model="moonshotai/kimi-k2-instruct-0905",
                messages=st.session_state.messages,
                max_completion_tokens=2048,
                temperature=0.7,
                stream=True
            )

            for chunk in stream:
                if (
                    chunk.choices
                    and chunk.choices[0].delta
                    and chunk.choices[0].delta.content
                ):
                    token = chunk.choices[0].delta.content
                    full_response += token
                    placeholder.markdown(full_response)

        # Handle empty response
        if full_response.strip() == "":
            full_response = "No response from the model."

        st.session_state.messages.append(
            {"role": "assistant", "content": full_response}
        )