# # # HEAD
# import streamlit as st
# from groq import Groq
# import os
# from dotenv import load_dotenv

# load_dotenv()

# # 🔹 Page UI
# st.set_page_config(page_title="KimiAI Bot", page_icon=":robot_face:", layout="centered")
# st.title("KimiAI Bot generated by UmarImam")
# st.caption("Powered by Groq API")

# client = Groq(api_key=os.getenv("GROQ_API_KEY"))

# # 🔹 Session Memory
# if "messages" not in st.session_state:
#     st.session_state.messages = []

# # 🔹 Display Chat History
# for msg in st.session_state.messages:
#     with st.chat_message(msg["role"]):
#         st.markdown(msg["content"])

# # 🔹 User Input
# prompt = st.chat_input("Ask me anything...")

# if prompt:
#     # Store user message
#     st.session_state.messages.append({"role": "user", "content": prompt})

#     # 👇 Immediately show user message
#     with st.chat_message("user"):
#         st.markdown(prompt)

#     full_response = ""

#     stream = client.chat.completions.create(
#         model="moonshotai/kimi-k2-instruct-0905",
#         messages=st.session_state.messages,
#         max_completion_tokens=2048,
#         temperature=0.7,
#         stream=True
#     )

#     with st.chat_message("assistant"):
#         placeholder = st.empty()

#         for chunk in stream:
#             if chunk.choices and chunk.choices[0].delta.content:
#                 token = chunk.choices[0].delta.content
#                 full_response += token
#                 placeholder.markdown(full_response)

#     if full_response.strip() == "":
#         full_response = "No response from the model"

#     st.session_state.messages.append(
#         {"role": "assistant", "content": full_response}
#     )

# # 🔹 Footer
# st.markdown("---")
# st.markdown(
#     "<div style='text-align: center; color: gray;'>Made with ❤️ — KimiAI Bot generated by UmarImam</div>",
#     unsafe_allow_html=True
# )
# =======

# # above was sir code and below is mine code


import streamlit as st
from groq import Groq

# ---------------------------
# Page Config
# ---------------------------
st.set_page_config(
    page_title="KimiAI Bot",
    page_icon="🤖",
    layout="centered"
)

# ---------------------------
# Custom Styling
# ---------------------------
st.markdown("""
<style>
.block-container {
    padding-top: 1rem;
}
</style>
""", unsafe_allow_html=True)

st.markdown("""
<div style="text-align: center;">
    <h1>KimiAI Bot 🤖</h1>
    <p style="color: gray; position: relative; left: -15px;">
        Powered by Groq API
    </p>
</div>
""", unsafe_allow_html=True)

# ---------------------------
# Sidebar
# ---------------------------
with st.sidebar:
    st.title("⚙️ Settings")

    if st.button("➕ New Chat"):
        st.session_state.messages = []
        st.rerun()

    if st.button("🗑️ Clear Chat"):
        st.session_state.messages = []
        st.rerun()

    st.markdown(
        """
        <div style='margin-top:40px;'>
            <hr>
            <div style='text-align:center; font-size:20px; color:white; font-weight:600;
                        # text-shadow: 0px 0px 6px rgba(255,255,255,0.6);'>
                Made with ❤️ — <b>KimiAI Bot</b><br>
                <span style='font-size:18px; font-weight:500;'>
                    Developed by <b>Umar Imam</b>
                </span>
            </div>
        </div>
        """,
        unsafe_allow_html=True
    )

# ---------------------------
# API Key (Production Safe)
# ---------------------------
if "GROQ_API_KEY" not in st.secrets:
    st.error("API Key not found. Please set GROQ_API_KEY in Streamlit Secrets.")
    st.stop()

client = Groq(api_key=st.secrets["GROQ_API_KEY"])

# ---------------------------
# Session Memory
# ---------------------------
if "messages" not in st.session_state:
    st.session_state.messages = []

# ---------------------------
# Display Chat History
# ---------------------------
for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])

# ---------------------------
# User Input
# ---------------------------
prompt = st.chat_input("Ask me anything...")

if prompt:
    # Store user message
    st.session_state.messages.append({"role": "user", "content": prompt})

    # Immediately show user message
    with st.chat_message("user"):
        st.markdown(prompt)

    full_response = ""

    stream = client.chat.completions.create(
        model="moonshotai/kimi-k2-instruct-0905",
        messages=st.session_state.messages,
        max_completion_tokens=2048,
        temperature=0.7,
        stream=True
    )

    with st.chat_message("assistant"):
        placeholder = st.empty()

        for chunk in stream:
            if chunk.choices and chunk.choices[0].delta.content:
                token = chunk.choices[0].delta.content
                full_response += token
                placeholder.markdown(full_response)

    if full_response.strip() == "":
        full_response = "No response from the model"

    st.session_state.messages.append(
        {"role": "assistant", "content": full_response}
    )